"use strict";
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: commonpb/common.proto
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnvVar = exports.Process = exports.File = exports.Response = exports.Request = exports.Empty = exports.protobufPackage = void 0;
/* eslint-disable */
const wire_1 = require("@bufbuild/protobuf/wire");
exports.protobufPackage = "commonpb";
function createBaseEmpty() {
    return {};
}
exports.Empty = {
    encode(_, writer = new wire_1.BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEmpty();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return exports.Empty.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseEmpty();
        return message;
    },
};
function createBaseRequest() {
    return { Async: false, Timeout: "0", BeaconID: "", SessionID: "" };
}
exports.Request = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.Async !== false) {
            writer.uint32(8).bool(message.Async);
        }
        if (message.Timeout !== "0") {
            writer.uint32(16).int64(message.Timeout);
        }
        if (message.BeaconID !== "") {
            writer.uint32(66).string(message.BeaconID);
        }
        if (message.SessionID !== "") {
            writer.uint32(74).string(message.SessionID);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.Async = reader.bool();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.Timeout = reader.int64().toString();
                    continue;
                }
                case 8: {
                    if (tag !== 66) {
                        break;
                    }
                    message.BeaconID = reader.string();
                    continue;
                }
                case 9: {
                    if (tag !== 74) {
                        break;
                    }
                    message.SessionID = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            Async: isSet(object.Async) ? globalThis.Boolean(object.Async) : false,
            Timeout: isSet(object.Timeout) ? globalThis.String(object.Timeout) : "0",
            BeaconID: isSet(object.BeaconID) ? globalThis.String(object.BeaconID) : "",
            SessionID: isSet(object.SessionID) ? globalThis.String(object.SessionID) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.Async !== false) {
            obj.Async = message.Async;
        }
        if (message.Timeout !== "0") {
            obj.Timeout = message.Timeout;
        }
        if (message.BeaconID !== "") {
            obj.BeaconID = message.BeaconID;
        }
        if (message.SessionID !== "") {
            obj.SessionID = message.SessionID;
        }
        return obj;
    },
    create(base) {
        return exports.Request.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseRequest();
        message.Async = object.Async ?? false;
        message.Timeout = object.Timeout ?? "0";
        message.BeaconID = object.BeaconID ?? "";
        message.SessionID = object.SessionID ?? "";
        return message;
    },
};
function createBaseResponse() {
    return { Err: "", Async: false, BeaconID: "", TaskID: "" };
}
exports.Response = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.Err !== "") {
            writer.uint32(10).string(message.Err);
        }
        if (message.Async !== false) {
            writer.uint32(16).bool(message.Async);
        }
        if (message.BeaconID !== "") {
            writer.uint32(66).string(message.BeaconID);
        }
        if (message.TaskID !== "") {
            writer.uint32(74).string(message.TaskID);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.Err = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.Async = reader.bool();
                    continue;
                }
                case 8: {
                    if (tag !== 66) {
                        break;
                    }
                    message.BeaconID = reader.string();
                    continue;
                }
                case 9: {
                    if (tag !== 74) {
                        break;
                    }
                    message.TaskID = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            Err: isSet(object.Err) ? globalThis.String(object.Err) : "",
            Async: isSet(object.Async) ? globalThis.Boolean(object.Async) : false,
            BeaconID: isSet(object.BeaconID) ? globalThis.String(object.BeaconID) : "",
            TaskID: isSet(object.TaskID) ? globalThis.String(object.TaskID) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.Err !== "") {
            obj.Err = message.Err;
        }
        if (message.Async !== false) {
            obj.Async = message.Async;
        }
        if (message.BeaconID !== "") {
            obj.BeaconID = message.BeaconID;
        }
        if (message.TaskID !== "") {
            obj.TaskID = message.TaskID;
        }
        return obj;
    },
    create(base) {
        return exports.Response.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseResponse();
        message.Err = object.Err ?? "";
        message.Async = object.Async ?? false;
        message.BeaconID = object.BeaconID ?? "";
        message.TaskID = object.TaskID ?? "";
        return message;
    },
};
function createBaseFile() {
    return { Name: "", Data: Buffer.alloc(0) };
}
exports.File = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.Name !== "") {
            writer.uint32(10).string(message.Name);
        }
        if (message.Data.length !== 0) {
            writer.uint32(18).bytes(message.Data);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseFile();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.Name = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.Data = Buffer.from(reader.bytes());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            Name: isSet(object.Name) ? globalThis.String(object.Name) : "",
            Data: isSet(object.Data) ? Buffer.from(bytesFromBase64(object.Data)) : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.Name !== "") {
            obj.Name = message.Name;
        }
        if (message.Data.length !== 0) {
            obj.Data = base64FromBytes(message.Data);
        }
        return obj;
    },
    create(base) {
        return exports.File.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseFile();
        message.Name = object.Name ?? "";
        message.Data = object.Data ?? Buffer.alloc(0);
        return message;
    },
};
function createBaseProcess() {
    return { Pid: 0, Ppid: 0, Executable: "", Owner: "", Architecture: "", SessionID: 0, CmdLine: [] };
}
exports.Process = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.Pid !== 0) {
            writer.uint32(8).int32(message.Pid);
        }
        if (message.Ppid !== 0) {
            writer.uint32(16).int32(message.Ppid);
        }
        if (message.Executable !== "") {
            writer.uint32(26).string(message.Executable);
        }
        if (message.Owner !== "") {
            writer.uint32(34).string(message.Owner);
        }
        if (message.Architecture !== "") {
            writer.uint32(58).string(message.Architecture);
        }
        if (message.SessionID !== 0) {
            writer.uint32(40).int32(message.SessionID);
        }
        for (const v of message.CmdLine) {
            writer.uint32(50).string(v);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseProcess();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 8) {
                        break;
                    }
                    message.Pid = reader.int32();
                    continue;
                }
                case 2: {
                    if (tag !== 16) {
                        break;
                    }
                    message.Ppid = reader.int32();
                    continue;
                }
                case 3: {
                    if (tag !== 26) {
                        break;
                    }
                    message.Executable = reader.string();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }
                    message.Owner = reader.string();
                    continue;
                }
                case 7: {
                    if (tag !== 58) {
                        break;
                    }
                    message.Architecture = reader.string();
                    continue;
                }
                case 5: {
                    if (tag !== 40) {
                        break;
                    }
                    message.SessionID = reader.int32();
                    continue;
                }
                case 6: {
                    if (tag !== 50) {
                        break;
                    }
                    message.CmdLine.push(reader.string());
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            Pid: isSet(object.Pid) ? globalThis.Number(object.Pid) : 0,
            Ppid: isSet(object.Ppid) ? globalThis.Number(object.Ppid) : 0,
            Executable: isSet(object.Executable) ? globalThis.String(object.Executable) : "",
            Owner: isSet(object.Owner) ? globalThis.String(object.Owner) : "",
            Architecture: isSet(object.Architecture) ? globalThis.String(object.Architecture) : "",
            SessionID: isSet(object.SessionID) ? globalThis.Number(object.SessionID) : 0,
            CmdLine: globalThis.Array.isArray(object?.CmdLine) ? object.CmdLine.map((e) => globalThis.String(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.Pid !== 0) {
            obj.Pid = Math.round(message.Pid);
        }
        if (message.Ppid !== 0) {
            obj.Ppid = Math.round(message.Ppid);
        }
        if (message.Executable !== "") {
            obj.Executable = message.Executable;
        }
        if (message.Owner !== "") {
            obj.Owner = message.Owner;
        }
        if (message.Architecture !== "") {
            obj.Architecture = message.Architecture;
        }
        if (message.SessionID !== 0) {
            obj.SessionID = Math.round(message.SessionID);
        }
        if (message.CmdLine?.length) {
            obj.CmdLine = message.CmdLine;
        }
        return obj;
    },
    create(base) {
        return exports.Process.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseProcess();
        message.Pid = object.Pid ?? 0;
        message.Ppid = object.Ppid ?? 0;
        message.Executable = object.Executable ?? "";
        message.Owner = object.Owner ?? "";
        message.Architecture = object.Architecture ?? "";
        message.SessionID = object.SessionID ?? 0;
        message.CmdLine = object.CmdLine?.map((e) => e) || [];
        return message;
    },
};
function createBaseEnvVar() {
    return { Key: "", Value: "" };
}
exports.EnvVar = {
    encode(message, writer = new wire_1.BinaryWriter()) {
        if (message.Key !== "") {
            writer.uint32(10).string(message.Key);
        }
        if (message.Value !== "") {
            writer.uint32(18).string(message.Value);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof wire_1.BinaryReader ? input : new wire_1.BinaryReader(input);
        const end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEnvVar();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }
                    message.Key = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }
                    message.Value = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },
    fromJSON(object) {
        return {
            Key: isSet(object.Key) ? globalThis.String(object.Key) : "",
            Value: isSet(object.Value) ? globalThis.String(object.Value) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.Key !== "") {
            obj.Key = message.Key;
        }
        if (message.Value !== "") {
            obj.Value = message.Value;
        }
        return obj;
    },
    create(base) {
        return exports.EnvVar.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEnvVar();
        message.Key = object.Key ?? "";
        message.Value = object.Value ?? "";
        return message;
    },
};
function bytesFromBase64(b64) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return globalThis.Buffer.from(arr).toString("base64");
}
function isSet(value) {
    return value !== null && value !== undefined;
}
